export const styles = {
  container: {
    marginTop: '80px',
    maxWidth: '800px',
    margin: '0 auto',
    padding: '40px 20px',
    fontFamily: 'Arial, sans-serif',
    background: 'url(/path/to/fff3.jpg) no-repeat center center fixed',
    backgroundSize: 'cover',
    borderRadius: '10px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  title: {
    fontSize: '32px',
    fontWeight: 'bold',
    marginBottom: '30px',
    textAlign: 'center' as const,
    color: '#8B0000',
  },
  progressBar: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '30px',
    position: 'relative' as const,
    '::before': {
      content: '""',
      position: 'absolute',
      top: '50%',
      left: '0',
      right: '0',
      height: '2px',
      backgroundColor: '#8B0000',
      zIndex: 0,
    },
  },
  progressStep: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: '#d1c4e9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    color: '#8B0000',
    position: 'relative' as const,
    zIndex: 1,
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
  },
  progressStepActive: {
    backgroundColor: '#8B0000',
    color: '#fff',
    boxShadow: '0 0 0 3px rgba(124, 77, 255, 0.3)',
  },
  form: {
    backgroundColor: '#fff',
    padding: '30px',
    borderRadius: '8px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    marginTop: '20px',
  },
  step: {
    marginBottom: '30px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontWeight: 'bold',
    color: '#8B0000',
  },
  input: {
    width: '100%',
    padding: '12px',
    marginBottom: '15px',
    border: '1px solid #d1c4e9',
    borderRadius: '4px',
    fontSize: '16px',
    transition: 'border-color 0.3s ease',
    ':focus': {
      borderColor: '#7c4dff',
      outline: 'none',
    },
  },
  select: {
    width: '100%',
    padding: '12px',
    marginBottom: '15px',
    border: '1px solid #d1c4e9',
    borderRadius: '4px',
    fontSize: '16px',
    backgroundColor: '#fff',
    transition: 'border-color 0.3s ease',
    ':focus': {
      borderColor: '#7c4dff',
      outline: 'none',
    },
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '30px',
  },
  button: {
    backgroundColor: '#8B0000',
    color: '#fff',
    padding: '12px 20px',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
    transition: 'background-color 0.3s',
    ':hover': {
      backgroundColor: '#7e57c2',
    },
  },
  buttonPrimary: {
    backgroundColor: '#8B0000',
    color: '#fff',
    padding: '12px 20px',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
    transition: 'background-color 0.3s',
    ':hover': {
      backgroundColor: '#651fff',
    },
  },
  productItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '15px',
    padding: '15px',
    backgroundColor: '#f3e5f5',
    borderRadius: '4px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  infoText: {
    color: '#5e35b1',
    marginTop: '20px',
    fontSize: '14px',
    textAlign: 'center' as const,
  },
  qrImage: {
    width: '200px',
    height: '200px',
    marginBottom: '20px',
    display: 'block',
    margin: '0 auto',
    borderRadius: '4px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  imagePreview: {
    maxWidth: '100%',
    height: 'auto',
    marginTop: '20px',
    borderRadius: '4px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  summary: {
    marginTop: '30px',
    padding: '20px',
    backgroundColor: '#ede7f6',
    borderRadius: '8px',
  },
  summaryTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '10px',
    color: '#5e35b1',
  },
  summaryTotal: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#7c4dff',
  },
  verificationSection: {
    marginBottom: '20px',
    padding: '15px',
    backgroundColor: '#ede7f6',
    borderRadius: '8px',
  },
  verificationTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '10px',
    color: '#5e35b1',
  },
  verificationItem: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '5px',
    fontSize: '16px',
    color: '#3c3c3c',
  },
  verificationTotal: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#7c4dff',
  },
  verificationNote: {
    fontSize: '14px',
    color: '#5e35b1',
    marginTop: '20px',
    textAlign: 'center' as const,
  },
  errorText: {
    color: 'red',
    fontSize: '14px',
    marginBottom: '10px',
  },
  formGroup: {
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  exampleText: {
    fontSize: '14px',
    color: '#888',
    marginTop: '5px',
    marginBottom: '10px',
  },
};
